# Generated by Django 2.0.5 on 2020-04-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_namt',
            new_name='last_name',
        ),
    ]
